#!/usr/bin/env ruby
require 'yaml'

# quickly access sql databases
# (only works for rails apps right now)
# assumes dev environment, and mysql, will generalize later

dbfile = 'config/database.yml'
if File.exist?(dbfile)
  config = YAML::load(File.open(dbfile, 'r').read)
  dbdata = config['development']
  dbpasswd = (dbdata['password'] == nil) ? "" : " -p#{dbdata['password']} "
  argcmd = ARGV.join(' ')
  dbcmd = if config['default']['adaptor'] == 'mysql'
      "mysql -D#{dbdata['database']} -u#{dbdata['username']} #{dbpasswd} -e '#{argcmd}'"
    else
      "psql -A --pset footer -d #{dbdata['database']} -c '#{argcmd}'"
    end

  system(dbcmd) unless ( argcmd =~ /(drop|delete)/i )
else
  puts "Not in rails app"
end

