#!/usr/bin/env python
# crawl along a hub channel, next or previous, for an arbitrary number of steps
import os
import sys
import urllib2

def hubcrawl(url, direction, num_steps):
    for i in range(num_steps):
        print(url)
        request = urllib2.Request("%s/%s" % (url, direction[1:]))
        response = urllib2.urlopen(request)
        url = response.geturl()


def validate(url, direction, num_steps):
    if direction != "-n" and direction != "-p":
        print("%s should be either -n or -p" % direction)
        sys.exit(1)

    import re
    r = re.compile('^[0-9]+$')
    if not(r.match(num_steps)):
        print("%s should be an integer" % num_steps)
        sys.exit(2)

def main():
    if len(sys.argv) == 4:
        _, url, direction, num_steps = sys.argv
        validate(url, direction, num_steps)
        hubcrawl(url, direction, int(num_steps))
    else:
        print("Usage: ")
        print("    hubcrawl http://hub/foo/2018/05/23/01/01/01/01/cxhDs -n 10")
        print "  or "
        print("    hubcrawl http://hub/foo/2018/05/23/01/01/01/01/cxhDs -p 10")

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)
