#!/bin/bash
# Jenkins status lights at the command line
# by tlehman
#
# Assumes the following environment variables are defined:
#   JENKINS_PASSWORD
#   JENKINS_USERNAME
#   JENKINS_HOSTNAME

function jenkins_data_table() {
    curl --user $JENKINS_USERNAME:$JENKINS_PASSWORD https://$JENKINS_HOSTNAME/api/json 2> /dev/null | \
    ruby -rjson -e 'def colorize(text, color_code); "\e[#{color_code}m#{text}\e[0m"; end
    def colorize_blinking(text, color_code); "\e[#{color_code};5m#{text}\e[0m"; end
    def red(text); colorize(text, 31); end
    def red_anim(text); colorize_blinking(text, 31); end
    def green(text); colorize(text, 32); end
    def green_anim(text); colorize_blinking(text, 32); end

    JSON.parse(STDIN.read)["jobs"].each { |job|
        color = job["color"].gsub(/blue/, "green")
        puts self.send(color, job["name"])
    }'
}

jenkins_data_table
