#!/usr/bin/env ruby
# numlet gives you the number of the letter: a -> 1, b -> 2, ..., z -> 26

def usage
  puts "Usage: "
  puts "  numlet Z"
  exit 1
end

usage if ARGV.count == 0
letter = ARGV.first
number = (letter.downcase.ord - 'a'.ord) + 1

puts number

